SELECT ANIMAL_ID, NAME FROM(
    SELECT i.ANIMAL_ID, i.NAME,
            RANK() OVER(ORDER BY o.DATETIME - i.DATETIME DESC) 순위,
            o.DATETIME - i.DATETIME 크기
    FROM ANIMAL_OUTS o
    JOIN ANIMAL_INS i ON o.ANIMAL_ID = i.ANIMAL_ID
) WHERE 순위 <= 2
ORDER BY 크기 DESC;