SELECT p.PRODUCT_ID,PRODUCT_NAME, (PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY p.PRODUCT_ID, PRODUCT_NAME, PRICE
ORDER BY  TOTAL_SALES DESC, p.PRODUCT_ID;
