SELECT TITLE, r.BOARD_ID BOARD_ID, r.REPLY_ID REPLY_ID, r.WRITER_ID WRITER_ID, r.CONTENTS CONTENTS, TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD')CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID	
WHERE b.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD') AND b.CREATED_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
ORDER BY r.CREATED_DATE, TITLE;