SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK b
JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') AND
      SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;